// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwAMCUD3dG8Uxm9zE4wKQDBe7fsgazXfE',
    appId: '1:13149056802:web:8b902763942bf780b6ff7b',
    messagingSenderId: '13149056802',
    projectId: 'student-life-application',
    authDomain: 'student-life-application.firebaseapp.com',
    storageBucket: 'student-life-application.firebasestorage.app',
    measurementId: 'G-38DK94MXLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaJi698kxgvS0WP0xfuHVvGK_8k5nKA4s',
    appId: '1:13149056802:android:a4ade48d1f612619b6ff7b',
    messagingSenderId: '13149056802',
    projectId: 'student-life-application',
    storageBucket: 'student-life-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmX0H3Yove3YOgndCQsNv8_QLscHR_E0Y',
    appId: '1:13149056802:ios:3f04dc44262041aab6ff7b',
    messagingSenderId: '13149056802',
    projectId: 'student-life-application',
    storageBucket: 'student-life-application.firebasestorage.app',
    androidClientId: '13149056802-au6470g9iroefnusct1mv35cdr6jotss.apps.googleusercontent.com',
    iosClientId: '13149056802-d8ef278qeqjgjg1j3ivvht4gf90ikho0.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentLifeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmX0H3Yove3YOgndCQsNv8_QLscHR_E0Y',
    appId: '1:13149056802:ios:3f04dc44262041aab6ff7b',
    messagingSenderId: '13149056802',
    projectId: 'student-life-application',
    storageBucket: 'student-life-application.firebasestorage.app',
    androidClientId: '13149056802-au6470g9iroefnusct1mv35cdr6jotss.apps.googleusercontent.com',
    iosClientId: '13149056802-d8ef278qeqjgjg1j3ivvht4gf90ikho0.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentLifeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwAMCUD3dG8Uxm9zE4wKQDBe7fsgazXfE',
    appId: '1:13149056802:web:8b902763942bf780b6ff7b',
    messagingSenderId: '13149056802',
    projectId: 'student-life-application',
    authDomain: 'student-life-application.firebaseapp.com',
    storageBucket: 'student-life-application.firebasestorage.app',
    measurementId: 'G-38DK94MXLY',
  );

}